algoritmo "calcula-media2"
// Função :
// Autor :
// Data : 10/08/2023
// Seção de Declarações 
var
   cp,gp : inteiro
   vp,valor :real
inicio
      escreval("calcule o estoque médio de uma peça")
      escreval("Código da peça")
      leia(cp)
      escreval("Valor da peça")
      leia(vp)
      escreval("Quantidade de peças")
      leia(gp)
      valor <- (gp*vp)
      escreval("O código da peça",cp, " seu valor total é ", "R$",valor)
      
      
     
fimalgoritmo
