Algoritmo "Excercício_repetição03"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2023
Var
// Seção de Declarações das variáveis 
   i,n :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...


   

    
   

Fimalgoritmo